pipeline {
  agent any
  stages {
    stage('TF init & plan') {
      when { anyOf {branch "master";changeRequest() } }
      steps {
        withAWS(credentials: 'aws-oqf', region: 'us-east-1'){
          sh '''
              cd test/aws/terraform/ec2_role_share_rule/public_and_private_ec2_same_role
              terraform init
              terraform plan -out=plan.out
          '''
        }
      }
    }
  }
}    
