pipeline {
  agent any
  stages {
    stage('TF init & validate') {
      when { anyOf {branch "master";changeRequest() } }
      steps {
          sh '''
            cd test/aws/terraform/ensure_s3_buckets_encrypted_rule/encrypted/
            terraform init
            terraform validate'''
      }
    }

    stage('TF plan') {
      when { anyOf {branch "master";changeRequest() } }
      steps {
        withAWS(credentials: 'aws-oqf', region: 'us-east-1'){
          sh '''  
            cd test/aws/terraform/ensure_s3_buckets_encrypted_rule/encrypted/
            terraform plan'''
          }
        }
    }

    stage('TF Apply') {
      when { anyOf {branch "master" } }
      steps {
        withAWS(credentials: 'aws-oqf', region: 'us-east-1'){
          sh '''
            cd test/aws/terraform/ensure_s3_buckets_encrypted_rule/encrypted/
            terraform apply -input=false -auto-approve'''
          }
        }
      }
  }
}
